/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Robots = {
  noIndex?: boolean;
  noFollow?: boolean;
};

export type Gradient = {
  enabled?: boolean;
  color?: "red" | "blue" | "white";
  config?: Array<{
    direction?: "top" | "bottom" | "left" | "right";
    desktopDirection?: "top" | "bottom" | "left" | "right";
    size?: "xs" | "sm" | "md" | "lg";
    desktopSize?: "xs" | "sm" | "md" | "lg";
    color?: "red" | "blue" | "white";
    _type: "gradientConfig";
    _key: string;
  }>;
};

export type FilterPublications = {
  label?: string;
  filterFields?: FilterFields;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type FileDataFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  _type: "file";
};

export type FilterFields = {
  article?: string;
  news?: string;
  guide?: string;
  review?: string;
};

export type RichTextSection = {
  _type: "richTextSection";
  heading?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HeroPublicationsSection = {
  _type: "heroPublicationsSection";
  heading?: string;
  subheading?: string;
  publicationCounter?: string;
  badges?: Array<string>;
};

export type PublicationFilterSection = {
  _type: "publicationFilterSection";
  filterHeading?: string;
  searchbarPlaceholder?: string;
  publicationsPerPage?: number;
  filterPublications?: FilterPublications;
};

export type PatronitePerksSection = {
  _type: "patronitePerksSection";
  heading?: string;
  subheading?: string;
  caption?: string;
  tiers?: Array<{
    amount?: string;
    perks?: Array<string>;
    _type: "tier";
    _key: string;
  }>;
  cta?: Link;
};

export type IconCardSection = {
  _type: "iconCardSection";
  heading?: string;
  subheading?: string;
  items?: Array<{
    title?: string;
    subtitle?: string;
    icon?: Img;
    _type: "item";
    _key: string;
  }>;
};

export type BenefitsSection = {
  _type: "benefitsSection";
  heading?: string;
  benefits?: Array<{
    title?: string;
    image?: Img;
    _type: "benefit";
    _key: string;
  }>;
  cta?: Link;
};

export type DoubleHeroSection = {
  _type: "doubleHeroSection";
  heading?: string;
  headingText?: string;
  subheading?: string;
  subheadingText?: string;
  caption?: string;
  cta?: Link;
  image?: GradientImg;
};

export type DocumentsSection = {
  _type: "documentsSection";
  groups?: Array<{
    title?: string;
    items?: Array<
      | {
          file?: FileDataFile;
          title?: string;
          date?: string;
          _type: "fileData";
          _key: string;
        }
      | {
          title?: string;
          items?: Array<{
            file?: FileDataFile;
            title?: string;
            date?: string;
            _type: "fileData";
            _key: string;
          }>;
          _type: "documentSubgroup";
          _key: string;
        }
    >;
    _type: "documentGroup";
    _key: string;
  }>;
};

export type EventsListSection = {
  _type: "eventsListSection";
  dummy?: string;
};

export type ExpertsListSection = {
  _type: "expertsListSection";
  dummy?: string;
};

export type DivisionsListSection = {
  _type: "divisionsListSection";
  header?: string;
  text?: string;
};

export type UniversalHeroSection = {
  _type: "universalHeroSection";
  header?: string;
  description?: string;
  caption?: string;
  image?: GradientImg;
};

export type ContactSection = {
  _type: "contactSection";
  heading?: string;
  subtitle?: string;
  contactEmail?: string;
  contactAddress?: string;
  recipientEmail?: string;
};

export type SupportUsSection = {
  _type: "supportUsSection";
  heading?: string;
  subheading?: string;
  description?: string;
  cta?: Link;
  image?: Img;
};

export type PodcastSection = {
  _type: "podcastSection";
  heading?: string;
  subheading?: string;
  embed?: string;
  link?: Link;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type PeopleSection = {
  _type: "peopleSection";
  heading?: string;
  subheading?: string;
  link?: Link;
  people?: Array<{
    groupName?: string;
    members?: Array<
      {
        _key: string;
      } & PersonReference
    >;
    _type: "group";
    _key: string;
  }>;
};

export type NewPublicationsSection = {
  _type: "newPublicationsSection";
  heading?: string;
};

export type CardsWithLinkSection = {
  _type: "cardsWithLinkSection";
  heading?: string;
  subheading?: string;
  items?: Array<{
    title?: string;
    description?: string;
    icon?: Img;
    link?: Link;
    _type: "item";
    _key: string;
  }>;
};

export type HeroSection = {
  _type: "heroSection";
  heading?: string;
  subheading?: string;
  backgroundImage?: Img;
  cta?: Link;
  secondaryCta?: Link;
};

export type EventsSection = {
  _type: "eventsSection";
  heading?: string;
  link?: Link;
};

export type DivisionsSection = {
  _type: "divisionsSection";
  heading?: string;
  subheading?: string;
  description?: string;
};

export type AboutUsSection = {
  _type: "aboutUsSection";
  heading?: string;
  image?: Img;
  content?: Array<{
    text?: string;
    icon?: Img;
    _type: "column";
    _key: string;
  }>;
};

export type Breadcrumbs = Array<
  | ({
      _key: string;
    } & Link)
  | {
      text?: string;
      _type: "label";
      _key: string;
    }
>;

export type Socials = Array<{
  platform?:
    | "facebook"
    | "instagram"
    | "linkedin"
    | "twitter"
    | "youtube"
    | "spotify";
  url?: string;
  _type: "socialLink";
  _key: string;
}>;

export type PageBuilder = Array<
  | ({
      _key: string;
    } & AboutUsSection)
  | ({
      _key: string;
    } & DivisionsSection)
  | ({
      _key: string;
    } & EventsSection)
  | ({
      _key: string;
    } & HeroSection)
  | ({
      _key: string;
    } & CardsWithLinkSection)
  | ({
      _key: string;
    } & NewPublicationsSection)
  | ({
      _key: string;
    } & PeopleSection)
  | ({
      _key: string;
    } & PodcastSection)
  | ({
      _key: string;
    } & SupportUsSection)
  | ({
      _key: string;
    } & ContactSection)
  | ({
      _key: string;
    } & UniversalHeroSection)
  | ({
      _key: string;
    } & DivisionsListSection)
  | ({
      _key: string;
    } & ExpertsListSection)
  | ({
      _key: string;
    } & EventsListSection)
  | ({
      _key: string;
    } & DocumentsSection)
  | ({
      _key: string;
    } & DoubleHeroSection)
  | ({
      _key: string;
    } & BenefitsSection)
  | ({
      _key: string;
    } & IconCardSection)
  | ({
      _key: string;
    } & PatronitePerksSection)
  | ({
      _key: string;
    } & PublicationFilterSection)
  | ({
      _key: string;
    } & HeroPublicationsSection)
  | ({
      _key: string;
    } & RichTextSection)
>;

export type LinkButton = {
  _type: "linkButton";
  variant?: "primary" | "secondary" | "text" | "link";
  link?: Link;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type DivisionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "division";
};

export type PublicationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publication";
};

export type Link = {
  _type: "link";
  linkType?: "page" | "publication" | "division" | "href";
  text?: string;
  href?: string;
  page?: PageReference;
  division?: DivisionReference;
  publication?: PublicationReference;
  openInNewTab?: boolean;
  isExternal?: boolean;
};

export type PostsSection = {
  _type: "postsSection";
  displayNumber?: number;
};

export type LeadSection = {
  _type: "leadSection";
  title?: string;
  subtitle?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GradientImg = {
  _type: "gradientImg";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  gradient?: Gradient;
};

export type Img = {
  _type: "img";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonical?: string;
  ogImage?: Img;
  twitterCreator?: string;
  robots?: Robots;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  shortSiteName?: string;
  logo?: Img;
  baseUrl?: string;
  organization?: {
    name?: string;
    socials?: Array<string>;
    email?: string;
    phone?: string;
  };
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?: IconPicker;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type PersonGroups = {
  _id: string;
  _type: "personGroups";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  groups?: Array<{
    name?: InternationalizedArrayString;
    slug?: Slug;
    subgroups?: Array<{
      name?: InternationalizedArrayString;
      slug?: Slug;
      _type: "subgroup";
      _key: string;
    }>;
    _type: "group";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  group?: string;
  title?: InternationalizedArrayString;
  secondaryGroup?: string;
  secondaryTitle?: InternationalizedArrayString;
  img?: Img;
  bio?: InternationalizedArrayText;
  socials?: Socials;
  order?: number;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type NavigationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigation";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type TagCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tagCategory";
};

export type TranslationsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "translations";
};

export type PublicationTypeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publicationType";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | PageReference
    | EventReference
    | DivisionReference
    | NavigationReference
    | PublicationReference
    | TagReference
    | TagCategoryReference
    | TranslationsReference
    | PublicationTypeReference;
  language?: string;
};

export type Translations = {
  _id: string;
  _type: "translations";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  global?: {
    results?: string;
    search?: string;
  };
  navigation?: {
    home?: string;
    skipToContent?: string;
    menu?: string;
  };
  buttons?: {
    support?: string;
  };
  events?: {
    upcoming?: string;
    archive?: string;
    signUp?: string;
    noEvents?: string;
  };
  people?: {
    seeAll?: string;
    groupName?: string;
    allGroups?: string;
  };
  contactForm?: {
    starsign?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    subject?: string;
    message?: string;
    submit?: string;
    sending?: string;
    requiredError?: string;
    invalidEmail?: string;
    tooLong?: string;
    successTitle?: string;
    successMessage?: string;
    successClose?: string;
    errorMessage?: string;
    errorMessageWithEmail?: string;
    placeholders?: {
      firstName?: string;
      lastName?: string;
      email?: string;
      phone?: string;
      subject?: string;
      message?: string;
    };
  };
  divisions?: {
    divisionNotFound?: string;
    checkDetails?: string;
  };
  publications?: {
    cardButton?: string;
    groupName?: string;
    groupInitials?: string;
    showAuthors?: string;
    singlePublicationPage?: {
      breadcrumbHome?: string;
      breadcrumbsPublication?: string;
      share?: string;
      copied?: string;
      downloadPdf?: string;
      noImage?: string;
      inThisArticle?: string;
      noHeadings?: string;
      relatedPublicationTitle?: string;
      allPublications?: string;
      bibliography?: string;
    };
  };
  filterComponent?: {
    search?: string;
    category?: string;
    publicationsSearch?: string;
    results?: string;
    reset?: string;
    sortBy?: string;
    sortNewest?: string;
    sortOldest?: string;
    emptyState?: string;
    emptyStatePublicationsTitle?: string;
    emptyStatePublicationsDesc?: string;
    showAllPublications?: string;
    loading?: string;
    maxAmmount?: string;
  };
  notFound?: {
    title?: string;
    desc?: string;
    button?: string;
  };
  locale?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  slug?: Slug;
  category?: TagCategoryReference;
};

export type TagCategory = {
  _id: string;
  _type: "tagCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  description?: string;
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  type?: PublicationTypeReference;
  title?: string;
  excerpt?: string;
  slug?: Slug;
  date?: string;
  mainImage?: GradientImg;
  authors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  pdfFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  text?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          source?: string;
          url?: string;
          _type: "footnote";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PublicationType = {
  _id: string;
  _type: "publicationType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  title?: string;
  slug?: Slug;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: Img;
  logoText?: string;
  button?: Link;
  navigation?: Array<
    | {
        name?: string;
        items?: Array<
          {
            _key: string;
          } & Link
        >;
        _type: "dropdown";
        _key: string;
      }
    | ({
        _key: string;
      } & Link)
  >;
  contactInfo?: {
    email?: string;
    phone?: string;
    socials?: Socials;
    address?: string;
    identifiers?: string;
  };
  additionalLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  copyright?: string;
  madeBy?: string;
  madeByLink?: Link;
  locale?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  type?: string;
  startDate?: string;
  endDate?: string;
  isOnline?: boolean;
  division?: DivisionReference;
  venue?: string;
  address?: string;
  excerpt?: string;
  registrationUrl?: string;
};

export type Division = {
  _id: string;
  _type: "division";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  name?: string;
  sortName?: string;
  slug?: Slug;
  coverImage?: Img;
  pageBuilder?: PageBuilder;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  breadcrumbs?: Breadcrumbs;
  pageBuilder?: PageBuilder;
  locale?: string;
  seo?: Seo;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Robots
  | Gradient
  | FilterPublications
  | SanityFileAssetReference
  | FileDataFile
  | FilterFields
  | RichTextSection
  | HeroPublicationsSection
  | PublicationFilterSection
  | PatronitePerksSection
  | IconCardSection
  | BenefitsSection
  | DoubleHeroSection
  | DocumentsSection
  | EventsListSection
  | ExpertsListSection
  | DivisionsListSection
  | UniversalHeroSection
  | ContactSection
  | SupportUsSection
  | PodcastSection
  | PersonReference
  | PeopleSection
  | NewPublicationsSection
  | CardsWithLinkSection
  | HeroSection
  | EventsSection
  | DivisionsSection
  | AboutUsSection
  | Breadcrumbs
  | Socials
  | PageBuilder
  | LinkButton
  | PageReference
  | DivisionReference
  | PublicationReference
  | Link
  | PostsSection
  | LeadSection
  | SanityImageAssetReference
  | GradientImg
  | Img
  | RichText
  | Seo
  | Settings
  | Category
  | IconPicker
  | PersonGroups
  | Slug
  | InternationalizedArrayString
  | Person
  | InternationalizedArrayText
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | TranslationMetadata
  | InternationalizedArrayReference
  | EventReference
  | NavigationReference
  | TagReference
  | TagCategoryReference
  | TranslationsReference
  | PublicationTypeReference
  | InternationalizedArrayReferenceValue
  | Translations
  | Tag
  | TagCategory
  | Publication
  | SanityImageCrop
  | SanityImageHotspot
  | PublicationType
  | Navigation
  | Event
  | Division
  | Page
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;
